### ISSUE TITLE
Update for 3.18 on extensions.gnome.org?

### ISSUE THREAD

**Issue by Selena-Gomez** [EddieGz/guake-indicator#1]
Will there be an update available for this extension on the Gnome extensions site?

**Comment by EddyGz** [comment]
Is there a problem with the extension, for me it is still working (gnome
shell 3.16.4)?

It's very simple programming, feel free to advise your solution (or change
it yourself if you feel confident). Otherwise, tell me what the problem is.

greetz,
Eddy.

2015-12-31 7:27 GMT+01:00 Selena Gomez notifications@github.com:
